name: blue-recorder
base: core24
version: git
adopt-info: blue-recorder
title: Blue Recorder
summary: A simple screen recorder for Linux desktop. Supports Wayland & Xorg
license: GPL-3.0
contact: https://github.com/xlmnxp/blue-recorder/issues
website: https://github.com/xlmnxp/blue-recorder
issues: https://github.com/xlmnxp/blue-recorder/issues
source-code: https://github.com/xlmnxp/blue-recorder
donation: https://liberapay.com/xlmnxp
description: |
  A simple desktop recorder for Linux systems. Built using Rust, GTK+ 4 and ffmpeg. It supports recording audio and video on almost all Linux interfaces with support for Wayland display server on GNOME session.
  The following formats are currently supported: mkv, avi, mp4, wmv, gif and nut. You can stop the recording process easily by right-clicking the icon and choosing "Stop Record". Or middle-clicking the recording icon in the notifications area (but doesn't work on all interfaces).
  You can choose the audio input source you want from the list. You can also set the default values you want by simply changing them in the interface, and the program will save them for you for the next time you open it.
  Based on GREEN RECORDER but rewritten in RUST
grade: stable
confinement: strict
compression: lzo
environment:
  SNAP_DESKTOP_RUNTIME: $SNAP/gnome-platform

parts:
  blue-recorder:
    plugin: rust
    source: .
    rust-channel: stable
    rust-path: [gui]
    stage-snaps:
      - ffmpeg
    stage-packages:
      - x11-utils
      - pulseaudio-utils
      - libadwaita-1-0
      - libgstreamer-plugins-base1.0-0
      - libgstreamer1.0-0
      - libpipewire-0.3-0
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-pipewire
      - gstreamer1.0-x
    build-packages:
      - clang
      - gettext
      - build-essential
      - libadwaita-1-dev
      - libgstreamer-plugins-bad1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer1.0-dev
      - libgstreamer1.0-0
    override-build: |
      craftctl default
      cp -a data gui/interfaces locales $CRAFT_PART_INSTALL/
  cleanup:
    after: [blue-recorder]
    plugin: nil
    build-snaps: [gnome-46-2404]
    override-prime: |
      set -eux
      cd /snap/gnome-46-2404/current
      find . -type f,l -exec rm -f $CRAFT_PRIME/{} \;
      rm -f $CRAFT_PRIME/usr/lib/x86_64-linux-gnu/libwayland-client.so*
      rm -f $CRAFT_PRIME/usr/lib/x86_64-linux-gnu/libwayland-cursor.so*
      rm -f $CRAFT_PRIME/usr/lib/x86_64-linux-gnu/libwayland-egl.so*
      rm -f $CRAFT_PRIME/usr/lib/x86_64-linux-gnu/libwayland-server.so*
apps:
  blue-recorder:
    command: bin/blue-recorder
    desktop: data/snap/blue-recorder.desktop
    environment:
      SNAP_DESKTOP_RUNTIME: $SNAP/gnome-platform
      GTK_USE_PORTAL: '1'
      LC_DIR: $SNAP/locales
      DATA_DIR: $SNAP/data/
      GST_PLUGIN_PATH: $SNAP/usr/lib/x86_64-linux-gnu/gstreamer-1.0
    extensions:
      - gnome
    plugs:
      - desktop
      - home
      - audio-playback
      - audio-record
      - wayland
      - x11
      - pipewire
      - screencast-legacy # for wayland support
    slots:
      - dbus-daemon
    common-id: sa.sy.blue-recorder

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: sa.sy.blue-recorder