name: Test
on: [pull_request, push]
jobs:
  blue-recorder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Install dependencies
        run: |
          sudo apt-get install \
            librust-gstreamer-sys-dev \
            librust-gtk4-sys-dev \
            libunwind-dev \
            librust-gstreamer-sys-dev \
            librust-gdk-sys-dev \
            librust-atk-dev \
            librust-gtk4-sys-dev \
            libgdk-pixbuf-2.0-dev \
            librust-pango-dev \
            librust-gobject-sys-dev \
            ffmpeg
      - run: cargo test
